// client.ts - Supabase setup, don't leak these keys lol
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcfpbpdiomaxedwiyims.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZnBicGRpb21heGVkd2l5aW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTI2NDYsImV4cCI6MjA2ODUyODY0Nn0.Oi9WnBGlGEDQAkzaOJcQtVc7zeb-5s4XqwjpRqBK3vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});